### ISSUE TITLE
Get java.lang.ClassCastException when running of2

### ISSUE THREAD

**Issue by achabotl** [psidnell/ofexport2#10]
Hi,
I installed version 1.0.19 (2015-01-07) and get the following error when running `of2` with anything other than the `-h` option.

    $ ./of2 -v
    Loading...
    Exception in thread "main" java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double
        at org.psidnell.omnifocus.sqlite.SQLiteClassDescriptor.getValue(SQLiteClassDescriptor.java:135)
        at org.psidnell.omnifocus.sqlite.SQLiteClassDescriptor.load(SQLiteClassDescriptor.java:93)
        at org.psidnell.omnifocus.sqlite.SQLiteDAO.load(SQLiteDAO.java:125)
        at org.psidnell.omnifocus.sqlite.SQLiteDAO.load(SQLiteDAO.java:102)
        at org.psidnell.omnifocus.Main.loadData(Main.java:59)
        at org.psidnell.omnifocus.Main.main(Main.java:160) 

I have the following Java version:

    $ java -version
    java version "1.8.0_40"
    Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
    Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

And Omnifocus is version 2.1.1 (v92.6 r228096), Pro, bought from The OmniGroup.

**Comment by psidnell** [comment]
It looks like Wambold has fixed this - the joy of open source.

I'll try and roll a new release.

**Comment by achabotl** [comment]
Problem fixed for me. Thanks @wambold.
