### ISSUE TITLE
Java Exception `Cannot find class [org.psidnell.omnifocus.sqlite.SQLiteDataSource]` when running the latest master

### ISSUE THREAD

**Issue by kennonb** [psidnell/ofexport2#17]
Hi,

Not sure if this is a known issue and my experience with Java is limited so I'm not sure how to fix this. In the latest master release I'm seeing the following error when I try and run the app.

```
Exception in thread "main" org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.psidnell.omnifocus.sqlite.SQLiteDataSource] for bean with name 'sqLiteDS' defined in class path resource [config.xml]; nested exception is java.lang.ClassNotFoundException: org.psidnell.omnifocus.sqlite.SQLiteDataSource
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1325)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:623)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1394)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:957)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:742)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at org.psidnell.omnifocus.ApplicationContextFactory.getContext(ApplicationContextFactory.java:36)
	at org.psidnell.omnifocus.Main.main(Main.java:138)
Caused by: java.lang.ClassNotFoundException: org.psidnell.omnifocus.sqlite.SQLiteDataSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:249)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:395)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1346)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1317)
	... 11 more
```

* OF2 installed from the Omni website (v2.11.2)
* macOS High Sierra (10.13.2)
* Java 1.8.0_92

Is this just me missing a dependency somewhere? The release version works, but I was trying this one out because of a commit I saw that mentioned possibly working better with ASCII?

Thanks!

**Comment by psidnell** [comment]
I don't think that change affected dependencies, but sadly I don't have a working Mac any more so I'm merging in pull requests without running the S/W myself.

My main worry would be that the install/run scripts may be affected by newer versions of MacOS.

Sorry I can't be more help.

**Comment by kennonb** [comment]
Yea, I understand. Thanks @psidnell. 👍
